services:
  frontend-ms:
    build: ./frontend
    # image: laguilavo10/frontend-music-saver:latest
    container_name: frontend-ms
    ports:
      - 4200:4200
    volumes:
      - ./frontend:/app
      - /app/node_modules
  backend-ms:
    build: ./backend
    # image: laguilavo10/backend-music-saver:latest
    container_name: backend-ms
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app